# Generated by Django 6.0.6 on 2026-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.CharField(choices=[('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('+1', 'Plus One'), ('+2', 'Plus Two'), ('ug1', 'Degree 1st Year'), ('ug2', 'Degree 2nd Year'), ('ug3', 'Degree 3rd Year')], max_length=20),
        ),
    ]
