# Generated by Django 6.0.6 on 2026-06-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='marks',
            name='english',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='math',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='science',
        ),
        migrations.AddField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.subject'),
            preserve_default=False,
        ),
    ]
