# Generated by Django 6.0.6 on 2026-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subject_remove_marks_english_remove_marks_math_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='math',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='science',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
