# Generated by Django 6.0 on 2026-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_staff_rename_class_schoolclass_remove_note_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.CharField(choices=[('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('+1', 'Plus One'), ('+2', 'Plus Two'), ('ug1', 'Degree 1st Year'), ('ug2', 'Degree 2nd Year'), ('ug3', 'Degree 3rd Year')], max_length=10),
        ),
    ]
