# Generated by Django 6.0.6 on 2026-06-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_marks_subject_remove_marks_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='computer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='social',
            field=models.IntegerField(default=0),
        ),
    ]
