# Generated by Django 6.0.6 on 2026-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_subject_marks_computer_marks_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='computer',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='english',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='math',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='science',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='social',
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
