# Generated by Django 6.0 on 2026-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
