# Generated by Django 6.0 on 2026-06-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_studentremark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='note',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
