# Generated by Django 6.0.6 on 2026-06-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_marks_note_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('background', models.ImageField(blank=True, null=True, upload_to='school_bg/')),
            ],
        ),
    ]
